onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix unsigned /testbench_alu/z
add wave -noupdate -radix unsigned -childformat {{/testbench_alu/alucontrol(2) -radix unsigned} {/testbench_alu/alucontrol(1) -radix unsigned} {/testbench_alu/alucontrol(0) -radix unsigned}} -expand -subitemconfig {/testbench_alu/alucontrol(2) {-radix unsigned} /testbench_alu/alucontrol(1) {-radix unsigned} /testbench_alu/alucontrol(0) {-radix unsigned}} /testbench_alu/alucontrol
add wave -noupdate -radix decimal -childformat {{/testbench_alu/a(31) -radix decimal} {/testbench_alu/a(30) -radix decimal} {/testbench_alu/a(29) -radix decimal} {/testbench_alu/a(28) -radix decimal} {/testbench_alu/a(27) -radix decimal} {/testbench_alu/a(26) -radix decimal} {/testbench_alu/a(25) -radix decimal} {/testbench_alu/a(24) -radix decimal} {/testbench_alu/a(23) -radix decimal} {/testbench_alu/a(22) -radix decimal} {/testbench_alu/a(21) -radix decimal} {/testbench_alu/a(20) -radix decimal} {/testbench_alu/a(19) -radix decimal} {/testbench_alu/a(18) -radix decimal} {/testbench_alu/a(17) -radix decimal} {/testbench_alu/a(16) -radix decimal} {/testbench_alu/a(15) -radix decimal} {/testbench_alu/a(14) -radix decimal} {/testbench_alu/a(13) -radix decimal} {/testbench_alu/a(12) -radix decimal} {/testbench_alu/a(11) -radix decimal} {/testbench_alu/a(10) -radix decimal} {/testbench_alu/a(9) -radix decimal} {/testbench_alu/a(8) -radix decimal} {/testbench_alu/a(7) -radix decimal} {/testbench_alu/a(6) -radix decimal} {/testbench_alu/a(5) -radix decimal} {/testbench_alu/a(4) -radix decimal} {/testbench_alu/a(3) -radix decimal} {/testbench_alu/a(2) -radix decimal} {/testbench_alu/a(1) -radix decimal} {/testbench_alu/a(0) -radix decimal}} -expand -subitemconfig {/testbench_alu/a(31) {-radix decimal} /testbench_alu/a(30) {-radix decimal} /testbench_alu/a(29) {-radix decimal} /testbench_alu/a(28) {-radix decimal} /testbench_alu/a(27) {-radix decimal} /testbench_alu/a(26) {-radix decimal} /testbench_alu/a(25) {-radix decimal} /testbench_alu/a(24) {-radix decimal} /testbench_alu/a(23) {-radix decimal} /testbench_alu/a(22) {-radix decimal} /testbench_alu/a(21) {-radix decimal} /testbench_alu/a(20) {-radix decimal} /testbench_alu/a(19) {-radix decimal} /testbench_alu/a(18) {-radix decimal} /testbench_alu/a(17) {-radix decimal} /testbench_alu/a(16) {-radix decimal} /testbench_alu/a(15) {-radix decimal} /testbench_alu/a(14) {-radix decimal} /testbench_alu/a(13) {-radix decimal} /testbench_alu/a(12) {-radix decimal} /testbench_alu/a(11) {-radix decimal} /testbench_alu/a(10) {-radix decimal} /testbench_alu/a(9) {-radix decimal} /testbench_alu/a(8) {-radix decimal} /testbench_alu/a(7) {-radix decimal} /testbench_alu/a(6) {-radix decimal} /testbench_alu/a(5) {-radix decimal} /testbench_alu/a(4) {-radix decimal} /testbench_alu/a(3) {-radix decimal} /testbench_alu/a(2) {-radix decimal} /testbench_alu/a(1) {-radix decimal} /testbench_alu/a(0) {-radix decimal}} /testbench_alu/a
add wave -noupdate -radix unsigned -childformat {{/testbench_alu/b(31) -radix unsigned} {/testbench_alu/b(30) -radix unsigned} {/testbench_alu/b(29) -radix unsigned} {/testbench_alu/b(28) -radix unsigned} {/testbench_alu/b(27) -radix unsigned} {/testbench_alu/b(26) -radix unsigned} {/testbench_alu/b(25) -radix unsigned} {/testbench_alu/b(24) -radix unsigned} {/testbench_alu/b(23) -radix unsigned} {/testbench_alu/b(22) -radix unsigned} {/testbench_alu/b(21) -radix unsigned} {/testbench_alu/b(20) -radix unsigned} {/testbench_alu/b(19) -radix unsigned} {/testbench_alu/b(18) -radix unsigned} {/testbench_alu/b(17) -radix unsigned} {/testbench_alu/b(16) -radix unsigned} {/testbench_alu/b(15) -radix unsigned} {/testbench_alu/b(14) -radix unsigned} {/testbench_alu/b(13) -radix unsigned} {/testbench_alu/b(12) -radix unsigned} {/testbench_alu/b(11) -radix unsigned} {/testbench_alu/b(10) -radix unsigned} {/testbench_alu/b(9) -radix unsigned} {/testbench_alu/b(8) -radix unsigned} {/testbench_alu/b(7) -radix unsigned} {/testbench_alu/b(6) -radix unsigned} {/testbench_alu/b(5) -radix unsigned} {/testbench_alu/b(4) -radix unsigned} {/testbench_alu/b(3) -radix unsigned} {/testbench_alu/b(2) -radix unsigned} {/testbench_alu/b(1) -radix unsigned} {/testbench_alu/b(0) -radix unsigned}} -expand -subitemconfig {/testbench_alu/b(31) {-radix unsigned} /testbench_alu/b(30) {-radix unsigned} /testbench_alu/b(29) {-radix unsigned} /testbench_alu/b(28) {-radix unsigned} /testbench_alu/b(27) {-radix unsigned} /testbench_alu/b(26) {-radix unsigned} /testbench_alu/b(25) {-radix unsigned} /testbench_alu/b(24) {-radix unsigned} /testbench_alu/b(23) {-radix unsigned} /testbench_alu/b(22) {-radix unsigned} /testbench_alu/b(21) {-radix unsigned} /testbench_alu/b(20) {-radix unsigned} /testbench_alu/b(19) {-radix unsigned} /testbench_alu/b(18) {-radix unsigned} /testbench_alu/b(17) {-radix unsigned} /testbench_alu/b(16) {-radix unsigned} /testbench_alu/b(15) {-radix unsigned} /testbench_alu/b(14) {-radix unsigned} /testbench_alu/b(13) {-radix unsigned} /testbench_alu/b(12) {-radix unsigned} /testbench_alu/b(11) {-radix unsigned} /testbench_alu/b(10) {-radix unsigned} /testbench_alu/b(9) {-radix unsigned} /testbench_alu/b(8) {-radix unsigned} /testbench_alu/b(7) {-radix unsigned} /testbench_alu/b(6) {-radix unsigned} /testbench_alu/b(5) {-radix unsigned} /testbench_alu/b(4) {-radix unsigned} /testbench_alu/b(3) {-radix unsigned} /testbench_alu/b(2) {-radix unsigned} /testbench_alu/b(1) {-radix unsigned} /testbench_alu/b(0) {-radix unsigned}} /testbench_alu/b
add wave -noupdate -radix unsigned -childformat {{/testbench_alu/y(31) -radix unsigned} {/testbench_alu/y(30) -radix unsigned} {/testbench_alu/y(29) -radix unsigned} {/testbench_alu/y(28) -radix unsigned} {/testbench_alu/y(27) -radix unsigned} {/testbench_alu/y(26) -radix unsigned} {/testbench_alu/y(25) -radix unsigned} {/testbench_alu/y(24) -radix unsigned} {/testbench_alu/y(23) -radix unsigned} {/testbench_alu/y(22) -radix unsigned} {/testbench_alu/y(21) -radix unsigned} {/testbench_alu/y(20) -radix unsigned} {/testbench_alu/y(19) -radix unsigned} {/testbench_alu/y(18) -radix unsigned} {/testbench_alu/y(17) -radix unsigned} {/testbench_alu/y(16) -radix unsigned} {/testbench_alu/y(15) -radix unsigned} {/testbench_alu/y(14) -radix unsigned} {/testbench_alu/y(13) -radix unsigned} {/testbench_alu/y(12) -radix unsigned} {/testbench_alu/y(11) -radix unsigned} {/testbench_alu/y(10) -radix unsigned} {/testbench_alu/y(9) -radix unsigned} {/testbench_alu/y(8) -radix unsigned} {/testbench_alu/y(7) -radix unsigned} {/testbench_alu/y(6) -radix unsigned} {/testbench_alu/y(5) -radix unsigned} {/testbench_alu/y(4) -radix unsigned} {/testbench_alu/y(3) -radix unsigned} {/testbench_alu/y(2) -radix unsigned} {/testbench_alu/y(1) -radix unsigned} {/testbench_alu/y(0) -radix unsigned}} -expand -subitemconfig {/testbench_alu/y(31) {-radix unsigned} /testbench_alu/y(30) {-radix unsigned} /testbench_alu/y(29) {-radix unsigned} /testbench_alu/y(28) {-radix unsigned} /testbench_alu/y(27) {-radix unsigned} /testbench_alu/y(26) {-radix unsigned} /testbench_alu/y(25) {-radix unsigned} /testbench_alu/y(24) {-radix unsigned} /testbench_alu/y(23) {-radix unsigned} /testbench_alu/y(22) {-radix unsigned} /testbench_alu/y(21) {-radix unsigned} /testbench_alu/y(20) {-radix unsigned} /testbench_alu/y(19) {-radix unsigned} /testbench_alu/y(18) {-radix unsigned} /testbench_alu/y(17) {-radix unsigned} /testbench_alu/y(16) {-radix unsigned} /testbench_alu/y(15) {-radix unsigned} /testbench_alu/y(14) {-radix unsigned} /testbench_alu/y(13) {-radix unsigned} /testbench_alu/y(12) {-radix unsigned} /testbench_alu/y(11) {-radix unsigned} /testbench_alu/y(10) {-radix unsigned} /testbench_alu/y(9) {-radix unsigned} /testbench_alu/y(8) {-radix unsigned} /testbench_alu/y(7) {-radix unsigned} /testbench_alu/y(6) {-radix unsigned} /testbench_alu/y(5) {-radix unsigned} /testbench_alu/y(4) {-radix unsigned} /testbench_alu/y(3) {-radix unsigned} /testbench_alu/y(2) {-radix unsigned} /testbench_alu/y(1) {-radix unsigned} /testbench_alu/y(0) {-radix unsigned}} /testbench_alu/y
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {350 ps} {1350 ps}
