onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix decimal -childformat {{/testbench_alu/a(31) -radix decimal} {/testbench_alu/a(30) -radix decimal} {/testbench_alu/a(29) -radix decimal} {/testbench_alu/a(28) -radix decimal} {/testbench_alu/a(27) -radix decimal} {/testbench_alu/a(26) -radix decimal} {/testbench_alu/a(25) -radix decimal} {/testbench_alu/a(24) -radix decimal} {/testbench_alu/a(23) -radix decimal} {/testbench_alu/a(22) -radix decimal} {/testbench_alu/a(21) -radix decimal} {/testbench_alu/a(20) -radix decimal} {/testbench_alu/a(19) -radix decimal} {/testbench_alu/a(18) -radix decimal} {/testbench_alu/a(17) -radix decimal} {/testbench_alu/a(16) -radix decimal} {/testbench_alu/a(15) -radix decimal} {/testbench_alu/a(14) -radix decimal} {/testbench_alu/a(13) -radix decimal} {/testbench_alu/a(12) -radix decimal} {/testbench_alu/a(11) -radix decimal} {/testbench_alu/a(10) -radix decimal} {/testbench_alu/a(9) -radix decimal} {/testbench_alu/a(8) -radix decimal} {/testbench_alu/a(7) -radix decimal} {/testbench_alu/a(6) -radix decimal} {/testbench_alu/a(5) -radix decimal} {/testbench_alu/a(4) -radix decimal} {/testbench_alu/a(3) -radix decimal} {/testbench_alu/a(2) -radix decimal} {/testbench_alu/a(1) -radix decimal} {/testbench_alu/a(0) -radix decimal}} -subitemconfig {/testbench_alu/a(31) {-height 16 -radix decimal} /testbench_alu/a(30) {-height 16 -radix decimal} /testbench_alu/a(29) {-height 16 -radix decimal} /testbench_alu/a(28) {-height 16 -radix decimal} /testbench_alu/a(27) {-height 16 -radix decimal} /testbench_alu/a(26) {-height 16 -radix decimal} /testbench_alu/a(25) {-height 16 -radix decimal} /testbench_alu/a(24) {-height 16 -radix decimal} /testbench_alu/a(23) {-height 16 -radix decimal} /testbench_alu/a(22) {-height 16 -radix decimal} /testbench_alu/a(21) {-height 16 -radix decimal} /testbench_alu/a(20) {-height 16 -radix decimal} /testbench_alu/a(19) {-height 16 -radix decimal} /testbench_alu/a(18) {-height 16 -radix decimal} /testbench_alu/a(17) {-height 16 -radix decimal} /testbench_alu/a(16) {-height 16 -radix decimal} /testbench_alu/a(15) {-height 16 -radix decimal} /testbench_alu/a(14) {-height 16 -radix decimal} /testbench_alu/a(13) {-height 16 -radix decimal} /testbench_alu/a(12) {-height 16 -radix decimal} /testbench_alu/a(11) {-height 16 -radix decimal} /testbench_alu/a(10) {-height 16 -radix decimal} /testbench_alu/a(9) {-height 16 -radix decimal} /testbench_alu/a(8) {-height 16 -radix decimal} /testbench_alu/a(7) {-height 16 -radix decimal} /testbench_alu/a(6) {-height 16 -radix decimal} /testbench_alu/a(5) {-height 16 -radix decimal} /testbench_alu/a(4) {-height 16 -radix decimal} /testbench_alu/a(3) {-height 16 -radix decimal} /testbench_alu/a(2) {-height 16 -radix decimal} /testbench_alu/a(1) {-height 16 -radix decimal} /testbench_alu/a(0) {-height 16 -radix decimal}} /testbench_alu/a
add wave -noupdate -radix decimal /testbench_alu/b
add wave -noupdate -radix decimal -childformat {{/testbench_alu/y(31) -radix decimal} {/testbench_alu/y(30) -radix decimal} {/testbench_alu/y(29) -radix decimal} {/testbench_alu/y(28) -radix decimal} {/testbench_alu/y(27) -radix decimal} {/testbench_alu/y(26) -radix decimal} {/testbench_alu/y(25) -radix decimal} {/testbench_alu/y(24) -radix decimal} {/testbench_alu/y(23) -radix decimal} {/testbench_alu/y(22) -radix decimal} {/testbench_alu/y(21) -radix decimal} {/testbench_alu/y(20) -radix decimal} {/testbench_alu/y(19) -radix decimal} {/testbench_alu/y(18) -radix decimal} {/testbench_alu/y(17) -radix decimal} {/testbench_alu/y(16) -radix decimal} {/testbench_alu/y(15) -radix decimal} {/testbench_alu/y(14) -radix decimal} {/testbench_alu/y(13) -radix decimal} {/testbench_alu/y(12) -radix decimal} {/testbench_alu/y(11) -radix decimal} {/testbench_alu/y(10) -radix decimal} {/testbench_alu/y(9) -radix decimal} {/testbench_alu/y(8) -radix decimal} {/testbench_alu/y(7) -radix decimal} {/testbench_alu/y(6) -radix decimal} {/testbench_alu/y(5) -radix decimal} {/testbench_alu/y(4) -radix decimal} {/testbench_alu/y(3) -radix decimal} {/testbench_alu/y(2) -radix decimal} {/testbench_alu/y(1) -radix decimal} {/testbench_alu/y(0) -radix decimal}} -subitemconfig {/testbench_alu/y(31) {-height 16 -radix decimal} /testbench_alu/y(30) {-height 16 -radix decimal} /testbench_alu/y(29) {-height 16 -radix decimal} /testbench_alu/y(28) {-height 16 -radix decimal} /testbench_alu/y(27) {-height 16 -radix decimal} /testbench_alu/y(26) {-height 16 -radix decimal} /testbench_alu/y(25) {-height 16 -radix decimal} /testbench_alu/y(24) {-height 16 -radix decimal} /testbench_alu/y(23) {-height 16 -radix decimal} /testbench_alu/y(22) {-height 16 -radix decimal} /testbench_alu/y(21) {-height 16 -radix decimal} /testbench_alu/y(20) {-height 16 -radix decimal} /testbench_alu/y(19) {-height 16 -radix decimal} /testbench_alu/y(18) {-height 16 -radix decimal} /testbench_alu/y(17) {-height 16 -radix decimal} /testbench_alu/y(16) {-height 16 -radix decimal} /testbench_alu/y(15) {-height 16 -radix decimal} /testbench_alu/y(14) {-height 16 -radix decimal} /testbench_alu/y(13) {-height 16 -radix decimal} /testbench_alu/y(12) {-height 16 -radix decimal} /testbench_alu/y(11) {-height 16 -radix decimal} /testbench_alu/y(10) {-height 16 -radix decimal} /testbench_alu/y(9) {-height 16 -radix decimal} /testbench_alu/y(8) {-height 16 -radix decimal} /testbench_alu/y(7) {-height 16 -radix decimal} /testbench_alu/y(6) {-height 16 -radix decimal} /testbench_alu/y(5) {-height 16 -radix decimal} /testbench_alu/y(4) {-height 16 -radix decimal} /testbench_alu/y(3) {-height 16 -radix decimal} /testbench_alu/y(2) {-height 16 -radix decimal} /testbench_alu/y(1) {-height 16 -radix decimal} /testbench_alu/y(0) {-height 16 -radix decimal}} /testbench_alu/y
add wave -noupdate /testbench_alu/dut/a
add wave -noupdate /testbench_alu/dut/b
add wave -noupdate /testbench_alu/dut/alucontrol
add wave -noupdate /testbench_alu/dut/result
add wave -noupdate /testbench_alu/dut/zero
add wave -noupdate /testbench_alu/dut/ADD_result
add wave -noupdate /testbench_alu/dut/SLT_result
add wave -noupdate /testbench_alu/dut/not_equal
add wave -noupdate /testbench_alu/dut/invers_b
add wave -noupdate /testbench_alu/dut/adder_b
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1203 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 257
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {803 ps} {1642 ps}
